# It run based on hosts
- name: 1.1 Filesystem Configuration
  hosts: Dev
  become: yes
  
  tasks:
  - name: "1.1.1.1 Ensure mounting of {{ item }} filesystems is disabled"
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      state: present
      regexp: "^(#)?install {{ item }}(\\s|$)"
      line: "install {{ item }} /bin/true"
      create: yes
    loop:
      - cramfs
      - freevxfs
      - jffs2
      - hfs
      - hfsplus
      - squashfs
      - udf
      - vfat

