# It run based on hosts
- name: 3 Network Configuration
  hosts: RedHat
  become: yes

  tasks:
  # 3.1.1 Ensure IP forwarding is disabled
  - sysctl:
      name: net.ipv4.ip_forward
      value: '0'
      state: present
  # 3.1.2 Ensure packet redirect sending is disabled
  - sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: '0'
      state: present

  - sysctl:
      name: net.ipv4.conf.default.send_redirects
      value: '0'
      state: present

  # 3.2 Network Parameters
  # 3.2.1 Ensure source routed packets are not accepted
  - sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: '0'
      state: present

  - sysctl:
      name: net.ipv4.conf.default.accept_source_route
      value: '0'
      state: present

  # 3.2.2 Ensure ICMP redirects are not accepted
  - sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: '0'
      state: present

  - sysctl:
      name: net.ipv4.conf.default.accept_redirects
      value: '0'
      state: present

  # 3.2.3 Ensure secure ICMP redirects are not accepted
  - sysctl:
      name: net.ipv4.conf.all.secure_redirects
      value: '0'
      state: present

  - sysctl:
      name: net.ipv4.conf.default.secure_redirects
      value: '0'
      state: present

  # 3.2.4 Ensure suspicious packets are logged
  - sysctl:
      name: net.ipv4.conf.all.log_martians
      value: '1'
      state: present

  - sysctl:
      name: net.ipv4.conf.default.log_martians
      value: '1'
      state: present

  # 3.2.5 Ensure broadcast ICMP requests are ignored 
  - sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'
      state: present

  # 3.2.6 Ensure bogus ICMP responses are ignored 
  - sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'
      state: present

  # 3.2.7 Ensure Reverse Path Filtering is enabled
  - sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '1'
      state: present

  - sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: '1'
      state: present

  # 3.2.8 Ensure TCP SYN Cookies is enabled
  - sysctl:
      name: net.ipv4.tcp_syncookies
      value: '1'
      state: present

  # 3.3 IPv6
  # 3.3.1 Ensure IPv6 router advertisements are not accepted 
  - sysctl:
      name: net.ipv6.conf.all.accept_ra
      value: '0'
      state: present

  - sysctl:
      name: net.ipv6.conf.default.accept_ra
      value: '0'
      state: present

  # 3.3.2 Ensure IPv6 redirects are not accepted
  - sysctl:
      name: net.ipv6.conf.all.accept_redirects
      value: '0'
      state: present

  - sysctl:
      name: net.ipv6.conf.default.accept_redirects
      value: '0'
      state: present

  # update all:
  - sysctl:
      name: net.ipv4.route.flush
      value: '1'
      state: present

  - name: 3.3.3 Ensure IPv6 is disabled
    lineinfile:
      path: /boot/grub2/grub.cfg
      state: present
      regexp: "^(#)GRUB_CMDLINE_LINUX="
      line: GRUB_CMDLINE_LINUX="ipv6.disable=1"
      create: yes

  - name: 3.3.3 Ensure IPv6 is disabled
    command: grub2-mkconfig > /boot/grub2/grub.cfg

  - name: 3.4.1 Ensure TCP Wrappers is installed
    yum:
      name: "{{ packages }}"
      state: installed
    vars:
      packages:
      - tcp_wrappers
      - tcp_wrappers-libs
 
  - name: "3.4.4 Ensure permissions on /etc/hosts.allow are 644"
    file:
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: '0644'
      
  - name: "3.4.5 Ensure permissions on /etc/hosts.deny are 644"
    file:
      dest: /etc/hosts.deny
      owner: root
      group: root
      mode: '0644'

  - name: 3.5 Uncommon Network Protocols - 3.5. "{{ item.no }}" Ensure "{{ item.name }}" is disabled"
    lineinfile:
      path: /etc/modprobe.d/CIS.conf
      state: present
      regexp: "^(#)?install {{ item.name }}(\\s|$)"
      line: "install {{ item.name }} /bin/true"
      create: yes
    loop:
      - { no: '1', name: 'dccp' }
      - { no: '2', name: 'sctp' }
      - { no: '3', name: 'rds' }
      - { no: '4', name: 'tipc' }

  - name: 3.6.1 Ensure iptables is installed
    yum:
      name: iptables
      state: latest
