# It run based on hosts
# 6 System Maintenance
- name: 6.1 System File Permissions 
  hosts: All
  become: yes

  tasks:
  # 6.1.2 Ensure permissions on /etc/passwd are configured
  - name: 6.1."{{ item.no }}" Ensure permissions on "{{ item.path }}" are configured
    file:
      path: "{{ item.path }}" 
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    with_items:
      - { no: 2, path: /etc/passwd, owner: root, group: root, mode: '0644' }
      - { no: 3, path: /etc/shadow, owner: root, group: root, mode: '0000' }
      - { no: 4, path: /etc/group, owner: root, group: root, mode: '0644' }
      - { no: 5, path: /etc/gshadow , owner: root, group: root, mode: '0000' }
      - { no: 6, path: /etc/passwd-, owner: root, group: root, mode: '0644' }
      - { no: 7, path: /etc/shadow-, owner: root, group: root, mode: '0000' }
      - { no: 8, path: /etc/group-, owner: root, group: root, mode: '0644' }
      - { no: 9, path: /etc/gshadow- , owner: root, group: root, mode: '0000' }
