# It run based on hosts
- name: 5.2 SSH Server Configuration
  hosts: Dev

  tasks:
  - name: "6.1.2 Ensure permissions on /etc/passwd are configured"
    file:
      dest: /etc/passwd
      owner: root
      group: root
      mode: 0644

- name: "6.1.3 Ensure permissions on /etc/shadow are configured"
  file:
      dest: /etc/shadow
      owner: root
      group: root
      mode: 0000

- name: "6.1.4 Ensure permissions on /etc/group are configured"
  file:
      dest: /etc/group
      owner: root
      group: root
      mode: 0644
