# It run based on hosts
- name: Fixed security compliance
  hosts: list_hosts

  tasks:
  - name: "5.2.8 Ensure SSH root login is disabled"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: ^#?PermitRootLogin
      line: PermitRootLogin no
      validate: sshd -tf %s
      notify: reload sshd
